"""Add start board field to prevent editing generated values

Revision ID: 1d8ad3924668
Revises: e0aef05497e3
Create Date: 2023-08-21 08:42:21.228083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8ad3924668'
down_revision: Union[str, None] = 'e0aef05497e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('start_board_str', sa.String(length=81), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'start_board_str')
    # ### end Alembic commands ###
